### ISSUE TITLE
Support for TI ADS1256

### ISSUE THREAD

**Issue by iurly** [fivdi/mcp-spi-adc#4]
Hi,
Would you consider a pull request adding support for the ADS1256 from TI?
It's a 24-bit SPI ADC available on a commodity shield called Waveshare High Precision AD/DA.
Proper handling would require multiple SPI transactions and individual pin management (reset, data ready etc).
Additional features are PGA, differential readings etc.
However, basic handling seems to work with minimal changes on top of your current implementation.
Would you take such changes into consideration?

**Comment by fivdi** [comment]
Hi @iurly, the ADS1256 has a lot more features than the MCP3xxx chips currently supported by mcp-spi-adc. The additional features include things such as data rate, multiplexer settings, PGA setting, calibration, etc. I therefore think it would make more sense to create a new Node.js module for the ADS1256 rather than extending mcp-spi-adc to support it. If you'd like to create a module for the ADS1256 feel free to use whatever you like from mcp-spi-adc.

**Comment by iurly** [comment]
Hi @fivdi,
thanks for the prompt response. 
I see your point and agree with you. 
On the other hand, I'm not really into adding full support for the whole feature set as I won't have the time to run proper testing and I just need basic functionality.
As a matter of fact it's only after stealing your code that I came to realize I could add limited support for the new chip with minimal changes and in the end the new module would just look 95% identical to yours.
Plus I'd have to also duplicate the wrapper module for node-red which is where I actually need it in the end.
Anway, if I really have to make a new module, please let me know how I can give you proper credit (e.g. in package.json -- I'm very new to npm).
Thanks!

**Comment by fivdi** [comment]
> Anway, if I really have to make a new module

It's best to create a new module. 

> please let me know how I can give you proper credit (e.g. in package.json -- I'm very new to npm).

You don't have to. If you want to, maybe add a line to the README for your module, something like this:

Inspired by [mcp-spi-adc](https://github.com/fivdi/mcp-spi-adc).
